# Site settings
title: R-SquareD
email: chinggis.f.khaan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tips and tricks I've learned over the years using R. I test
  new ideas and play with new technology. I work mostly in the
  financial services space.
baseurl: "https://dariustg.github.io/" # the subpath of your site, e.g. /blog/
url: "https://dariustg.github.io" # the base hostname & protocol for your site
twitter_username: dariustg
github_username:  dariustg
permalink: /:year/:month/:title.html
fig_width: 10
fig_height: 6

# Build settings
markdown: kramdown
